### ISSUE TITLE
Update 2.7.6 has blank Settings for Posts and Pages/Settings comments/Translation screen

### ISSUE THREAD

**Issue by JerryJaz** [AlexAlexandru/rating-system#11]
Of the four tabs, only the documentation tab shows content. First three are blank.

**Comment by AlexAlexandru** [comment]
Hello.Can you use inspect element?http://imgur.com/a/UExti

**Comment by AlexAlexandru** [comment]
Also you can try again with the latest github version?

**Comment by AlexAlexandru** [comment]
Update to 2.7.6.1

**Comment by JerryJaz** [comment]
Well done, thank you!
