### ISSUE TITLE
Problem with browser on Android and iOS

### ISSUE THREAD

**Issue by vicnip** [AlexAlexandru/rating-system#3]
Original I have 1 like and 0 dislike.  It is okay on a desktop browser.  When I tapped on the like on a mobile device, null replaced 1.  I tapped on dislike and null replaced 0.  This happened on "Internet" and "Firefox" on Android, and Safari on iPad mini.  I have not tried on other browsers on mobile devices.  

Please fix, because it is great otherwise.  Thanks!

**Comment by AlexAlexandru** [comment]
Hello.I have tried the version from https://wordpress.org/plugins/rating-system/  ?

**Comment by vicnip** [comment]
Yes.  That's the version I am using.  Should I post the question there?

**Comment by vicnip** [comment]
In any case, my WP version is 4.3.1.

**Comment by AlexAlexandru** [comment]
Can you give me a link to you website?

**Comment by vicnip** [comment]
Here you are: http://sample6.uaid.net/index.php/coupon/pr001-1/

Thanks!

**Comment by AlexAlexandru** [comment]
Can you create an temporary admin account and email it at vortexthemes@mail.com ?
