### ISSUE TITLE
Comment order at the top

### ISSUE THREAD

**Issue by tsplancer** [AlexAlexandru/rating-system#5]
Hello, 

Was wondering if possible to have the highest rated comment at the top instead of the bottom?Currently, the top rated comment shows up on the bottom and most disliked shows up on top or second. Thank you for making this great plugin and hope to hear from you soon.

**Comment by AlexAlexandru** [comment]
If you install this version is working https://github.com/VortexThemes/rating-system/archive/master.zip  ?

**Comment by tsplancer** [comment]
Hi Alex,

With this version, the top rated comment does go to the top, but the most disliked comment does not always go to the bottom. Sometimes ends up as second comment, but when refreshing few times, goes to the bottom. Thanks for the quick response and will definitely be donating.

**Comment by AlexAlexandru** [comment]
The was this was implemented doesn't work in the latest version of wordpress.I removed this option.
